# Generated by Django 3.2.5 on 2021-07-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0002_alter_ad_ad_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseadvertising',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='baseadvertising',
            name='views',
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_by_ip', models.CharField(max_length=16)),
                ('time_clicked', models.DateTimeField(auto_now=True)),
                ('seen_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising_management.baseadvertising')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_by_ip', models.CharField(max_length=16)),
                ('time_clicked', models.DateTimeField(auto_now=True)),
                ('clicked_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertising_management.baseadvertising')),
            ],
        ),
    ]
