# Generated by Django 3.2.5 on 2021-07-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0003_auto_20210714_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seen',
            old_name='time_clicked',
            new_name='time_showed',
        ),
        migrations.RemoveField(
            model_name='seen',
            name='clicked_by_ip',
        ),
        migrations.AddField(
            model_name='seen',
            name='seen_by_ip',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
    ]
