# Generated by Django 3.2.5 on 2021-07-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0004_auto_20210715_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
