# Generated by Django 3.2.5 on 2021-07-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0005_ad_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='clicked_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', related_query_name='clicks', to='advertising_management.baseadvertising'),
        ),
        migrations.AlterField(
            model_name='seen',
            name='seen_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', related_query_name='ad_views', to='advertising_management.baseadvertising'),
        ),
    ]
