# Generated by Django 3.2.5 on 2021-07-15 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0006_auto_20210715_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time_clicked',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 3, 34, 9, 25859)),
        ),
        migrations.AlterField(
            model_name='seen',
            name='time_showed',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 3, 34, 9, 27620)),
        ),
    ]
