# Generated by Django 3.2.5 on 2021-07-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0007_auto_20210715_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time_clicked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seen',
            name='time_showed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
