# Generated by Django 3.2.5 on 2021-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0008_auto_20210715_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadvertising',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseadvertising',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
