# Generated by Django 3.2.5 on 2021-07-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_management', '0009_auto_20210715_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadvertising',
            name='click_per_view',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baseadvertising',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
